-- Eliminar las tablas si existen
DROP TABLE IF EXISTS "PUBLIC"."CONEXIONES";
DROP TABLE IF EXISTS "PUBLIC"."CLIENTES";
DROP TABLE IF EXISTS "PUBLIC"."PEDIDOS";

-- Crear tabla CLIENTES
CREATE CACHED TABLE "PUBLIC"."CLIENTES"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
    "NOMBRE" CHARACTER VARYING(100),
    "DIRECCION" CHARACTER VARYING(255),
    "TELEFONO" CHARACTER VARYING(20)
);

-- Insertar datos en CLIENTES
INSERT INTO "PUBLIC"."CLIENTES" (NOMBRE, DIRECCION, TELEFONO) VALUES
('Joel', 'manco inca', '99999999'),
('Jorge', 'Manco inca', '94975487'),
('rossie', 'pampacancha', '99449494'),
('Rossi', 'pampacancha', '902995586');

-- Crear tabla CONEXIONES
CREATE CACHED TABLE "PUBLIC"."CONEXIONES"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
    "NOMBRE_CONEXION" CHARACTER VARYING(100) UNIQUE,
    "TIPO_CONEXION" CHARACTER VARYING(50),
    "MEDIDAS_CORTE" CHARACTER VARYING(100),
    "MEDIDAS_CAMPANAS" CHARACTER VARYING(100),
    "MEDIDAS_DE_CORTE_DE_SALIDAS" CHARACTER VARYING(100),
    "MEDIDAS_DE_CAMPANAS_DE_SALIDAS" CHARACTER VARYING(100),
    "TIPO_USO" CHARACTER VARYING(20) NOT NULL,
    "PRECIO" DECIMAL(10, 2)
);

-- Insertar datos en CONEXIONES
INSERT INTO "PUBLIC"."CONEXIONES" 
(NOMBRE_CONEXION, TIPO_CONEXION, MEDIDAS_CORTE, MEDIDAS_CAMPANAS, 
MEDIDAS_DE_CORTE_DE_SALIDAS, MEDIDAS_DE_CAMPANAS_DE_SALIDAS, TIPO_USO, PRECIO) VALUES
('Codo 6" x 45 Gris', 'Codo', '34 cm', 'null', 'null', 'null', 'alcantarillado', 10.00),
('Tee de 4"x 2"', 'Tee', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Base de 8"x 8"', 'Base', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Base de 8"x 6"', 'Base', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Base de 8"x 4"', 'Base', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Base de 8"x 4"(110mm) Naranja', 'Base', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Base de 6"x 6"', 'Base', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Base de 6"x 4"', 'Base', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Base de 6"x 4" (110mm)', 'Base', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Base de 6"x 4" (110mm) en Yee', 'Base', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Base de 6"x 2"', 'Base', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Base de 4"(110mm) x 4"(110mm) Naranja', 'Base', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Base de 4" x 4"', 'Base', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Base de 4" x 2"', 'Base', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Base de 4"(110mm) Naranja x 2"', 'Base', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Base de 2" x 2"', 'Base', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Yee de 8"x 8"', 'Yee', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Yee de 8"x 6"', 'Yee', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Yee de 8"x 4"', 'Yee', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Yee de 6"x 6"', 'Yee', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Yee de 6"x 4"', 'Yee', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Yee de 6"x 4" (110mm)', 'Yee', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Yee de 6"x 2"', 'Yee', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Yee de 4"(110mm) x 4"(110mm) Naranja', 'Yee', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Yee de 4"x 2"', 'Yee', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Union de 8" (200mm) Naranja', 'Union', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Union de 6" (160mm) Naranja', 'Union', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Union de 4" (110mm) Naranja', 'Union', NULL, NULL, NULL, NULL, 'alcantarillado', NULL),
('Union de 4" Desague Gris', 'Union', NULL, NULL, NULL, NULL, 'desague', NULL),
('Union de 2" Desague Gris', 'Union', NULL, NULL, NULL, NULL, 'desague', NULL),
('Union de 4" (SAP) Gris', 'Union', NULL, NULL, NULL, NULL, 'electrica', NULL),
('Union de 3" (SAP) Gris', 'Union', NULL, NULL, NULL, NULL, 'electrica', NULL),
('Union de 2" (SAP) Gris', 'Union', NULL, NULL, NULL, NULL, 'electrica', NULL),
('Union de 8" Naranja', 'Union', '25', NULL, NULL, NULL, 'alcantarillado', 9.00),
('Union de 6" (Agua) Naranja', 'Union', NULL, NULL, NULL, NULL, 'agua', NULL),
('Union de 4" (Agua) Naranja', 'Union', NULL, NULL, NULL, NULL, 'agua', NULL),
('Union de 3" (Agua) Gris', 'Union', NULL, NULL, NULL, NULL, 'agua', NULL),
('Union de 2 1/2" (Agua) Gris', 'Union', NULL, NULL, NULL, NULL, 'agua', NULL),
('Union de 2" (Agua) Gris', 'Union', NULL, NULL, NULL, NULL, 'agua', NULL),
('Union de 1 1/2" (Agua) Gris', 'Union', NULL, NULL, NULL, NULL, 'agua', NULL),
('Union de 1" (Agua) Gris', 'Union', NULL, NULL, NULL, NULL, 'agua', NULL),
('Curva de 4" SAP', 'Curva', NULL, NULL, NULL, NULL, 'electrica', NULL),
('Curva de 3" SAP', 'Curva', NULL, NULL, NULL, NULL, 'electrica', NULL),
('Curva de 2" SAP', 'Curva', NULL, NULL, NULL, NULL, 'electrica', NULL),
('Curva de 1 1/2" SAP', 'Curva', NULL, NULL, NULL, NULL, 'electrica', NULL),
('Curva de 1 1/4" SAP', 'Curva', NULL, NULL, NULL, NULL, 'electrica', NULL),
('Curva de 1" Agua', 'Curva', NULL, NULL, NULL, NULL, 'electrica', NULL),
('Curva de 3/4" Agua', 'Curva', NULL, NULL, NULL, NULL, 'electrica', NULL),
('Codo 6"x 90 Naranja', 'Codo', '37.3 cm', NULL, NULL, NULL, 'alcantarillado', 10.00),
('Codo 6"x45 Naranja', 'Codo', '31.3cm', NULL, NULL, NULL, 'agua', 9.00);

-- Crear tabla PEDIDOS
CREATE CACHED TABLE "PUBLIC"."PEDIDOS"(
    "ID_PEDIDO" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
    "ESTADO_PEDIDO" CHARACTER VARYING(50),
    "OBSERVACIONES" CHARACTER VARYING,
    "PRECIO_TOTAL" DECIMAL(10, 2),
    "CLIENTE" CHARACTER VARYING(50),
    "FECHA_PEDIDO" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insertar datos en PEDIDOS
INSERT INTO "PUBLIC"."PEDIDOS" 
(ESTADO_PEDIDO, OBSERVACIONES, PRECIO_TOTAL, CLIENTE, FECHA_PEDIDO) VALUES
('En proceso', 'Observacion del pedido', 460.00, 'Pelo lacio', TIMESTAMP '2025-01-19 19:55:14'),
('Pendiente', 'Pedido nuevo', 1080.00, 'Cliente Nuevo', TIMESTAMP '2025-01-19 20:22:16');